### ISSUE TITLE
Training Classifier Problem

### ISSUE THREAD

**Issue by drorhunvural** [devalab/DeepPocket#16]
You are giving code block below as an example for Training Classifier 

`python train.py -m model.py --train_types scPDB_train0.types --test_types scPDB_test0.types -i 200000 --train_recmolcache scPDB_new.molcache2 --test_recmolcache scPDB_new.molcache2 -r val0 -o /model_saves/val9 --base_lr 0.001 --solver Adam `

You are using **--data_dir (-d) i**n train.py as below

```
 eptrain = molgrid.ExampleProvider(shuffle=True, stratify_receptor=True, labelpos=0,balanced=True,
                                      data_root=args.data_dir,recmolcache=args.train_recmolcache)
```

Where are you reading **data_dir** from? The training classifier example you shared does not have data_dir in the code block ?
'

**Comment by RishalAggarwal** [comment]
The data_dir argument is ignored (despite being passed) for the classification model as all the required data is present in the molcache files. It becomes relevant for the segmentation models
