### ISSUE TITLE
lack of gninatypes files

### ISSUE THREAD

**Issue by fengyuewuya** [devalab/DeepPocket#18]
Hi, I want to use the train_segmentation.py , but it is prompted that the gninatypes file is missing. Can you provide this part of the file?
or should I process these files?
THX

**Comment by RishalAggarwal** [comment]
if you are using a new dataset, you'd probably have to create them, if you are using a dataset we used in the publication then you can use the molcache files present in the dataset link provided on the README

**Comment by fengyuewuya** [comment]
Hi, I use the molcache holo4k.molcache2 and take the train_segmentation.py. 
The code:
python train_segmentation.py --train_types train_segmentation_data/seg_holo4k_train.types --test_types train_segmentation_data/seg_holo4k_test.types -d tmp_data/holo4k_cavity/holo4k/ --train_recmolcache train_segmentation_data/holo4k.molcache2 --test_recmolcache train_segmentation_data/holo4k.molcache2 -b 8 -o model_saves/seg9 -e 200 -r seg9

The error result:
![image](https://user-images.githubusercontent.com/19147255/201725471-39127a71-dac7-41f2-8261-e11023a95dca.png)

**Comment by fengyuewuya** [comment]
I can't find the directory named 4jpc_1 in the compressed package.
Can you show me your directory structure?

**Comment by fengyuewuya** [comment]
Hi, I use the molcache holo4k.molcache2 and take the train_segmentation.py.

The code:
python train_segmentation.py --train_types train_segmentation_data/seg_holo4k_train.types --test_types train_segmentation_data/seg_holo4k_test.types -d tmp_data/holo4k_cavity/holo4k/ --train_recmolcache train_segmentation_data/holo4k.molcache2 --test_recmolcache train_segmentation_data/holo4k.molcache2 -b 8 -o model_saves/seg9 -e 200 -r seg9

The error result:


I can't find the directory named 4jpc_1 in the compressed package.
Can you show me your directory structure?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devalab/DeepPocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 凌晨0:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devalab/DeepPocket] lack of gninatypes files (Issue #18)





 
Closed #18 as completed.

**Comment by RishalAggarwal** [comment]
I think your train recmolcache should be the scpdb recmocache

**Comment by fengyuewuya** [comment]
I take the scPDB molcache2 and types.
but there still report the error  as bellow.  
The code:
python train_segmentation.py 
--train_types train_segmentation_data/seg_scPDB_train9.types 
--test_types train_segmentation_data/seg_scPDB_test9.types 
-d data/ 
--train_recmolcache train_segmentation_data/scPDB_new.molcache2 
--test_recmolcache train_segmentation_data/scPDB_new.molcache2 
-b 8 
-o model_saves/seg9 
-e 200 
-r seg9


Error report:
![image](https://user-images.githubusercontent.com/19147255/201809641-a4f9c28c-324b-4ebd-ab63-b96f956daa17.png)

Maybe the package environment is wrong?
or
Some files are missing?

**Comment by fengyuewuya** [comment]
I have solved this problem by downloading the scPDB original data and set the data_dir.
Thx a lot.

**Comment by mainguyenanhvu** [comment]
@fengyuewuya have you re-run data preparation for a custom data? If yes, please help me. 

I am trying to use the instruction to prepare data for training a new classifier. 
I have stuck in make_types step because I can't find train.txt and test.txt files. 

Moreover, I have 4 questions:
1. If I want to add several pdb files to the available scPDB dataset, how can I complete it?
2. The instruction for preparing data only works for a single pdb file, does it? If not, I need to write a pipeline to wrap up it. 
3. How to prepare train.txt and test.txt files to run make_types.py?
4. Could you please show me which file/folder needed inputting from previous to each step?

I am tried on [this pdb](https://www.rcsb.org/structure/8BRA).

Thank you very much. 

p.s: I have asked in the issue https://github.com/devalab/DeepPocket/issues/26.

**Comment by Satansu** [comment]
> I have solved this problem by downloading the scPDB original data and set the data_dir. Thx a lot.

@fengyuewuya could you elaborate on how you fixed this issue? Because I've run into the exact same issue but no fix seems to work.
