### ISSUE TITLE
predict.py running error

### ISSUE THREAD

**Issue by tinyimp80** [devalab/DeepPocket#21]
Hi, I have some issues when running 'predict.py'.

It seems can't find 'class_checkpoint' and 'seg_checkpoint'.

`python predict.py -p Downloads/3g73.pdb -c first_model_fold1_best_test_auc_85001.pth.tar -s seg0_best_test_IOU_91.pth.tar -r 3`

> DeepPocket/predict.py:14: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/pairwise2.py:283: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
>   BiopythonDeprecationWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 3096.
>   PDBConstructionWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 3097.
>   PDBConstructionWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 3098.
>   PDBConstructionWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 3146.
>   PDBConstructionWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 3177.
>   PDBConstructionWarning,
> /home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain D is discontinuous at line 3218.
>   PDBConstructionWarning,
> ***** POCKET HUNTING BEGINS ***** 
> mkdir: cannot create directory ‘Downloads/3g73_nowat_out/pockets’: File exists
> ***** POCKET HUNTING ENDS ***** 
> Traceback (most recent call last):
>   File "DeepPocket/predict.py", line 87, in <module>
>     class_checkpoint=torch.load(args.class_checkpoint)
>   File "/home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/park/miniconda3/envs/torchdrug/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'first_model_fold1_best_test_auc_85001.pth.tar'

Plz help...!!
Thanks

**Comment by RishalAggarwal** [comment]
you need to download the class and seg checkpoint files that you would like to use from the link given in the readme

**Comment by tinyimp80** [comment]
Thanks!!
