### ISSUE TITLE
Pocket Probability

### ISSUE THREAD

**Issue by drorhunvural** [devalab/DeepPocket#23]
![image](https://user-images.githubusercontent.com/26056864/216732513-8c28ecd3-f946-47ff-afe9-a7b332976a4a.png)

The content of bary_centers_ranked.types is as follows

3 -5.8872820891631195 2.4274225254193103 16.306759363865474 /content/xxx_nowat.gninatypes
1 -3.399881608822576 0.7210002432695428 11.260844794031787 /content/xxx_nowat.gninatypes
2 4.8732080737995735 -7.189318852006624 6.719965229046755 /content/xxxx_nowat.gninatypes
6 -8.189112907608695 8.49208722826087 8.578613858695654 /content/xxxx_nowat.gninatypes
5 -11.534677691417235 3.978282288738218 31.699375888870517 /content/xxxx_nowat.gninatype

How do you calculate the druggability score for each pocket centre? I'm trying to learn the `Pocket Probability` calculation

**Comment by RishalAggarwal** [comment]
I need to write up code for this, will push an update soon, pull request welcome
