### ISSUE TITLE
Channels in training  script are different from those in your Supporting Information table s1

### ISSUE THREAD

**Issue by ckami12138** [devalab/DeepPocket#24]
Thanks for your great work. I have one quesion, in your training code, you use the first 14 channels in gninamap file, which are

> Hydrogen, PolarHydrogen, AliphaticCarbonXSHydrophobe, AliphaticCarbonXSNonHydrophobe, AromaticCarbonXSHydrophobe, AromaticCarbonXSNonHydrophobe, Nitrogen, NitrogenXSDonor, NitrogenXSDonorAcceptor, NitrogenXSAcceptor, Oxygen, OxygenXSDonor, OxygenXSDonorAcceptor and OxygenXSAcceptor

, However in Supporting Information table s1(https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.1c00799/suppl_file/ci1c00799_si_001.pdf), they are

> AliphaticCarbonXSHydrophobe, AliphaticCarbonXSNonHydrophobe, AromaticCarbonXSHydrophobe, AromaticCarbonXSNonHydrophobe, Bromine Iodine Chlorine Fluorine, Nitrogen NitrogenXSAcceptor, NitrogenXSDonor NitrogenXSDonorAcceptor, Oxygen OxygenXSAcceptor, OxygenXSDonorAcceptor OxygenXSDonor, Sulfur SulfurAcceptor, Phosphorus, Calcium, Zinc and GenericMetal Boron Manganese Magnesium Iron

why they are different, may I misunderstand something?

**Comment by RishalAggarwal** [comment]
Yes, gninamap file is used to create the gninatype files which specify the atom type a particular atom is. When these files are loaded into libmolgrid, libmolgrid assigns these atoms to different channels based on whether it is a "receptor" or a "ligand" atom and based on the atom type identity. The first 14 channels represent the receptor atoms - theres probably a better way to do this but its a hack that worked at the time. So the first 14 channels represent the atom types that are given in our supporting information.

**Comment by ckami12138** [comment]
Thank you for your quick response. So, you mean libmorgrid considers Bromine Iodine Chlorine Fluorine (which are 4 diferent channels in gninamap file) as channel 5 (number from 1), Nitrogen NitrogenXSAcceptor as channel 6 (which are 2 diferent channels in gninamap file) etc.. Is this right? So, what do the other 14 channels represent,  and where can I find the definition of the whole 28 channes in libmolgrid files?

**Comment by RishalAggarwal** [comment]
you can see the ligand atom types here: https://github.com/gnina/libmolgrid/blob/master/include/libmolgrid/atom_typer.h - the atom types are at the bottom of the file

**Comment by ckami12138** [comment]
So, does it mean that if I use the defaultGninaReceptorTyper, I wiil get the same representation of protein as in your paper?

**Comment by RishalAggarwal** [comment]
Yes you should when you load a grid with it, however you have to be careful not to save gninatypes files using that typer

**Comment by ckami12138** [comment]
Thank you very much for your patience. My doubts have been resolved. I will close this issue.
