### ISSUE TITLE
No output after running train_segmentation.py

### ISSUE THREAD

**Issue by Satansu** [devalab/DeepPocket#29]
Hi, I've been trying to run this code but keep running into issues while trying to run the segmentation code. 

First few times I tried to run that code, I got the same error as shown here from Issue #18 - https://github.com/devalab/DeepPocket/issues/18#issuecomment-1314680335 

I re-downloaded the "scPDB_new" file and tried running it again, and now the code doesn't show an error, but it doesn't show any output either. I checked wandb as well, and it doesn't show any output (the train.py output had no issues and was represented perfectly on wandb).

Here is my code (on Google Colab) -
!python /content/drive/MyDrive/DeepPocket/train_segmentation.py 
--train_types /content/drive/MyDrive/DeepPocket/seg_scPDB_train0.types 
--test_types /content/drive/MyDrive/DeepPocket/seg_scPDB_test0.types 
-d /content/drive/MyDrive/DeepPocket/data/
--train_recmolcache scPDB_new.molcache2
--test_recmolcache scPDB_new.molcache2 
-b 8 
-o /content/drive/MyDrive/DeepPocket/model_saves/seg0 
-e 200 -r seg0

And here is the output -
![image](https://github.com/devalab/DeepPocket/assets/114721324/e2dd35b4-32ed-4142-9c3c-2b07f7f1bf4b)

I've been trying to fix this for a week, not sure what else I could do here. Any fixes or suggestions would be appreciated.

**Comment by RishalAggarwal** [comment]
I have a slight suspicion this is a wandb issue, have you tried changing its version and retrying? Have you downloaded the scpdb dataset for the cavity files? You could also check the local repository of the wandb and see if theres some data being saved there. If you share the colab link I could try reproducing it

**Comment by Satansu** [comment]
Thanks for the suggestions! 
I tried changing the wandb version, going back till 0.14.0, no change. Nothing in the wandb repositories as well. It shows that the program just runs and crashes although there's no error output (from what I can see) which is very baffling.

I downloaded the 3.5GB compressed scPDB dataset from the original site, but I'm not sure how to extract the cavity6.mol2 files specifically from that.

I'd be happy to share the Colab link, if you could send your email ID I can give access to the link.

**Comment by RishalAggarwal** [comment]
If its getting killed without any errors it could also be a memory issue, try reducing the batch size?

**Comment by Satansu** [comment]
Tried it, still crashed. On Colab, it shows the the cell executed in 20-30s without any errors (it should take far longer than that), while on wandb it shows the cell running for 7-8 minutes before crashing. I'm not sure what to make of it honestly.

I'll try re-downloading all relevant files from the repository again and trying again.

**Comment by Satansu** [comment]
Hi, thanks, I've figured out how to fix that particular error. Had to re-download the original scPDB dataset and extract all the cavity6.mol2 files from there. 

I have a follow-up question - How do I read .molcache2 files? I can't find any documentation regarding .molcache2 files online and I want to read the "scPDB_new.molcache2" file. Accessing .mol2 files is simple enough, but I can't seem to find anything for .molcache2 files.

**Comment by RishalAggarwal** [comment]
molcache2 files are binary files, solely defined to be used by the program. Basically a compressed form of your pdb/mol files that would be quicker i/o
