### ISSUE TITLE
Broken Link to Model Checkpoints, "404 FILE NOT FOUND"

### ISSUE THREAD

**Issue by 1874Mercury** [devalab/DeepPocket#30]
The link provided in the README/documentation for downloading the prepared types, molcache, and saved model checkpoints seems to be broken. When attempting to access the resources through the link, it results in a 404 File Not Found error. 

Could you please look into this and provide an updated link or guidance on how to access these materials? 

Best regards.

**Comment by RishalAggarwal** [comment]
oh shoot! Thanks for bringing this to my attention. I'm working on it, will post a working link soon!

**Comment by RishalAggarwal** [comment]
I've updated the link, please let me know if you have any further trouble accessing the data
