### ISSUE TITLE
Issue with archived file

### ISSUE THREAD

**Issue by souvksinha** [devalab/DeepPocket#31]
Hi,

I want to use DeepPocket to make some predictions. For that, I think I need the checkpoint files of the models. I tried downloading the archived zip file in OneDrive but it seems like having an issue unzipping it. Every attempt to unzip the file results in errors indicating that the zip file is corrupted or damaged.

Could you please assist in resolving this issue?

Thanks

**Comment by RishalAggarwal** [comment]
oh ok give me a few days i'll try to fix this

**Comment by RishalAggarwal** [comment]
It should be fixed now, please check again

**Comment by souvksinha** [comment]
Yes, I can access those files now! thanks
