### ISSUE TITLE
Are there production models trained on all data, or just the CV models?

### ISSUE THREAD

**Issue by AsaBarthMaron** [devalab/DeepPocket#37]
The example `python predict.py -p protein.pdb -c first_model_fold1_best_test_auc_85001.pth.tar -s seg0_best_test_IOU_91.pth.tar -r 3` indicates using classification and segmentation models from specific folds for predictions. Are these the models that you would recommend we use for prediction? Or are there models trained on the entire dataset that we should use instead?

**Comment by RishalAggarwal** [comment]
Hey! Yeah I have not trained any production level models, but I would recommend using an ensemble of these models if that would help.

**Comment by AsaBarthMaron** [comment]
Makes sense, thank you very much!
